services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synacktive_api
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backend
  
  db:
    image: postgres:14
    container_name: synacktive_db
    restart: always
    env_file:
      - .env
    volumes:
      - synacktive_db:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - db

volumes:
  synacktive_db:
   
  
networks:
  backend: