services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: synacktive_api
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
  db:
    con